package com.liferay.docs.eventlisting.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the OfficialPosition service. Represents a row in the &quot;Event_OfficialPosition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.docs.eventlisting.model.impl.OfficialPositionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.docs.eventlisting.model.impl.OfficialPositionImpl}.
 * </p>
 *
 * @author Joe Bloggs
 * @see OfficialPosition
 * @see com.liferay.docs.eventlisting.model.impl.OfficialPositionImpl
 * @see com.liferay.docs.eventlisting.model.impl.OfficialPositionModelImpl
 * @generated
 */
public interface OfficialPositionModel extends BaseModel<OfficialPosition> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a official position model instance should use the {@link OfficialPosition} interface instead.
     */

    /**
     * Returns the primary key of this official position.
     *
     * @return the primary key of this official position
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this official position.
     *
     * @param primaryKey the primary key of this official position
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the official position ID of this official position.
     *
     * @return the official position ID of this official position
     */
    public long getOfficialPositionId();

    /**
     * Sets the official position ID of this official position.
     *
     * @param officialPositionId the official position ID of this official position
     */
    public void setOfficialPositionId(long officialPositionId);

    /**
     * Returns the name of this official position.
     *
     * @return the name of this official position
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this official position.
     *
     * @param name the name of this official position
     */
    public void setName(String name);

    /**
     * Returns the is_archived of this official position.
     *
     * @return the is_archived of this official position
     */
    public boolean getIs_archived();

    /**
     * Returns <code>true</code> if this official position is is_archived.
     *
     * @return <code>true</code> if this official position is is_archived; <code>false</code> otherwise
     */
    public boolean isIs_archived();

    /**
     * Sets whether this official position is is_archived.
     *
     * @param is_archived the is_archived of this official position
     */
    public void setIs_archived(boolean is_archived);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.liferay.docs.eventlisting.model.OfficialPosition officialPosition);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.liferay.docs.eventlisting.model.OfficialPosition> toCacheModel();

    @Override
    public com.liferay.docs.eventlisting.model.OfficialPosition toEscapedModel();

    @Override
    public com.liferay.docs.eventlisting.model.OfficialPosition toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
