package com.liferay.docs.eventlisting.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Worker service. Represents a row in the &quot;Event_Worker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.docs.eventlisting.model.impl.WorkerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.docs.eventlisting.model.impl.WorkerImpl}.
 * </p>
 *
 * @author Joe Bloggs
 * @see Worker
 * @see com.liferay.docs.eventlisting.model.impl.WorkerImpl
 * @see com.liferay.docs.eventlisting.model.impl.WorkerModelImpl
 * @generated
 */
public interface WorkerModel extends BaseModel<Worker> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a worker model instance should use the {@link Worker} interface instead.
     */

    /**
     * Returns the primary key of this worker.
     *
     * @return the primary key of this worker
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this worker.
     *
     * @param primaryKey the primary key of this worker
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the worker ID of this worker.
     *
     * @return the worker ID of this worker
     */
    public long getWorkerId();

    /**
     * Sets the worker ID of this worker.
     *
     * @param workerId the worker ID of this worker
     */
    public void setWorkerId(long workerId);

    /**
     * Returns the name of this worker.
     *
     * @return the name of this worker
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this worker.
     *
     * @param name the name of this worker
     */
    public void setName(String name);

    /**
     * Returns the lastname of this worker.
     *
     * @return the lastname of this worker
     */
    @AutoEscape
    public String getLastname();

    /**
     * Sets the lastname of this worker.
     *
     * @param lastname the lastname of this worker
     */
    public void setLastname(String lastname);

    /**
     * Returns the patronymic of this worker.
     *
     * @return the patronymic of this worker
     */
    @AutoEscape
    public String getPatronymic();

    /**
     * Sets the patronymic of this worker.
     *
     * @param patronymic the patronymic of this worker
     */
    public void setPatronymic(String patronymic);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.liferay.docs.eventlisting.model.Worker worker);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.liferay.docs.eventlisting.model.Worker> toCacheModel();

    @Override
    public com.liferay.docs.eventlisting.model.Worker toEscapedModel();

    @Override
    public com.liferay.docs.eventlisting.model.Worker toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
